### ISSUE TITLE
AVSWITCH proxy issues

### ISSUE THREAD

**Issue by anpin** [control4/docs-driverworks#10]
Hi, I've encountered two issues with AVSWITCH template:
- it doesn't implement audio balance handlers
- notification about output mute status doesn't change it to OFF state, however changing to ON state works as expected

**Comment by jmcgeeverC4** [comment]
Thanks for your feedback regarding the AVSWITCH template. We do realize that these templates are out of date. Also, we aren't planning any more work on enhancing these versions. However, we are currently in the process of developing a new set of driver development templates which includes the AV Proxies. While the issues you encountered won't be resolved in the current version they will be addressed in the near future.
