### ISSUE TITLE
Camera Preview Not Shown in Navigator

### ISSUE THREAD

**Issue by mojtabavi** [control4/docs-driverworks#21]
I'm Trying to Develop Driver for My IP Camera using Camera Proxy Template
All the things is good but camera Preview In Mobile not shown
H.264 and MJPEG URL Test Passed and MJPEG Preview looks good in composer
In phone Navigator, Stream Shows but Preview not shown

<img src="https://user-images.githubusercontent.com/63472358/156469657-d08e2cd8-2736-4795-b072-e9050b670a8d.png" alt="camera_preview" width="300"/>

<img src="https://user-images.githubusercontent.com/63472358/156469784-48fbc3a1-8303-4215-91ae-f1720ba76f3d.png" alt="composer_camera" width="300"/>

<img src="https://user-images.githubusercontent.com/63472358/156469809-a83fae5d-30f4-4ea6-a840-0024ea9e6498.png" alt="navigator_stream" width="300"/>

**Comment by dinolink22** [comment]
@mojtabavi the preview is not live, it's supposed to be a snapshot. In composer pro, in the Camera Test properties, does the snapshot test passes?

**Comment by mojtabavi** [comment]
The thumbnail is pulled from the snapshot URL. The snapshot URL is blank above.
