### ISSUE TITLE
Blind UI Stop grayed out

### ISSUE THREAD

**Issue by dinolink22** [control4/docs-driverworks#24]
I am creating a blind driver, I am using levels 0 to 100. I have the "can_stop" capability that is set to "true" so I can see the stop in the UI and in Composer Pro. I can stop it via Composer but on the UI the stop (middle icon) it's grayed out, how come it's grayed out? What's the logic to make it work?
I do send MOVING the notification with the ramp time and start level and target level so the system should know that it should let stop if needed, no? Am I missing something?
Thanks!

**Comment by spike411** [comment]
I'd suggest studying what the 2 Relay Blinds (OS2.9+) / 3 Relay Blinds (OS2.9+) drivers do (both the code, which is nice and clean, and the debug log messages). They are provided by Control4 in the online database.

**Comment by dinolink22** [comment]
> I'd suggest studying what the 2 Relay Blinds (OS2.9+) / 3 Relay Blinds (OS2.9+) drivers do (both the code, which is nice and clean, and the debug log messages). They are provided by Control4 in the online database.

That's what i did, and i had the same core code so it was supposed to work, found a data error somewhere else that was importing the wrong data without causing any bug so corrected that and it's all good now, but thanks for the help!
