### ISSUE TITLE
Thermostat Capabilities typos

### ISSUE THREAD

**Issue by spike411** [control4/docs-driverworks#3]
https://control4.github.io/docs-driverworks-proxyprotocol/#thermostat-capabilities

All of the links to the `DYNAMIC_CAPABILITIES_CHANGED` section have the same typo: DYNAMIC_CA**PB**ILITIES_CHANGED
Morever, all of the links lead to the `DYNAMIC_CAPABILITY_CHANGED` section under the Light_V2 proxy section (including the link in the  navigation side panel):
https://control4.github.io/docs-driverworks-proxyprotocol/#dynamic-capabilities-changed

**Comment by jmcgeeverC4** [comment]
This has been resolved. Thanks for the feedback.
